# Site settings
title: Aarón Ojeda's personal site
description: Aarón Ojeda's personal site
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Aarón Ojeda
user_description: Self-motivated, analytical and creative software engineer. One way or another, I have been linked to video games professionally, personally or academically during my whole life. Needless to say, I love them. My thesis was about 2D platformers development with C++ and SDL. Leaving aside video games, I have experience in data science and a deep knowledge on basketball.
user_title: Software Engineer | Game Developer
email: aaron.ojeda.reyes@gmail.com
# twitter_username: lorem_ipsum
github_username: aaronojeda
# gplus_username:  lorem_ipsum
linkedin_username: aaojeda

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']

# Project descriptions
project_AG: <b>American Girl World</b> is a visual novel taking place in the world of American Girl, the popular line of dolls of Mattel.
project_HempInc: <b>Hemp Inc - Weed & Marijuana Business Game</b> is a simulation game where you start from scratch with the goal of building your own cannabis empire.
project_S2PEditor: Game engine and GUI for the development of 2D platform games in Windows. S2PEditor stands for <b>SDL 2D Platformer Editor</b>.
project_ThinkB4: My entry for Ludum Dare 39 was <b>Think before you jump</b>, a micro-platformer where jumping costs power. It has four levels and four different endings.
project_Epione: Co-founder of <b>e-pione</b>, startup with the aim of finding machine learning solutions for the diagnosis of neurological diseases.
